/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Tue Sep 11 10:43:55 2018. */

#include "service.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HeaderMessage_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HeaderMessage, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t UInt32Pair_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, UInt32Pair, key, key, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, UInt32Pair, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t VerifyMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, VerifyMessage, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, VerifyMessage, data, id, 0),
    PB_LAST_FIELD
};

const pb_field_t ShutdownCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ShutdownCommand, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, ShutdownCommand, type, id, 0),
    PB_LAST_FIELD
};

const pb_field_t ConfigCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ConfigCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ConfigCommand, config, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t DriverConfigCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DriverConfigCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DriverConfigCommand, config, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t MotionControlMotorCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotionControlMotorCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, MotionControlMotorCommand, command, id, &MotionControlMotorCommand_MotorCommandPair_fields),
    PB_LAST_FIELD
};

const pb_field_t MotionControlMotorCommand_MotorCommandPair_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotionControlMotorCommand_MotorCommandPair, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MotionControlMotorCommand_MotorCommandPair, command, id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DeviceCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DeviceCommand, command, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t ManualModeDeviceCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ManualModeDeviceCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ManualModeDeviceCommand, command, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t RemoteCommand433_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, RemoteCommand433, id, id, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, RemoteCommand433, command, id, 0),
    PB_LAST_FIELD
};

const pb_field_t ClearErrorCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ClearErrorCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ClearErrorCommand, bits, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t SaveMotorDriverConfigCommand_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SaveMotorDriverConfigCommand, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorDriverConfigCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotorDriverConfigCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, MotorDriverConfigCommand, config, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t MCUUpgradeCommand_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MCUUpgradeCommand, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MCUUpgradeCommand, time, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, MCUUpgradeCommand, num, time, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, MCUUpgradeCommand, check_code, num, 0),
    PB_FIELD(  5, BYTES   , REPEATED, CALLBACK, OTHER, MCUUpgradeCommand, command, check_code, 0),
    PB_LAST_FIELD
};

const pb_field_t CameraPTZCommand_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CameraPTZCommand, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CameraPTZCommand, command_id, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, CameraPTZCommand, data_1, command_id, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, CameraPTZCommand, data_2, data_1, 0),
    PB_LAST_FIELD
};

const pb_field_t MCUUpgradeStatusData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MCUUpgradeStatusData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MCUUpgradeStatusData, status, id, 0),
    PB_LAST_FIELD
};

const pb_field_t VersionData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, VersionData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, VersionData, version, id, &VersionData_VersionStruct_fields),
    PB_LAST_FIELD
};

const pb_field_t VersionData_VersionStruct_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, VersionData_VersionStruct, board, board, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, VersionData_VersionStruct, type, board, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, VersionData_VersionStruct, major, type, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, VersionData_VersionStruct, minor, major, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, VersionData_VersionStruct, build, minor, 0),
    PB_LAST_FIELD
};

const pb_field_t HealthData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HealthData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HealthData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DeviceData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DeviceData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t OdometryData_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, OdometryData, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, OdometryData, left_count, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, OdometryData, right_count, left_count, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, OdometryData, left_delta_count, right_count, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, OdometryData, right_delta_count, left_delta_count, 0),
    PB_LAST_FIELD
};

const pb_field_t IMUData_fields[14] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, IMUData, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, IMUData, roll, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, IMUData, pitch, roll, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, IMUData, yaw, pitch, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, angular_velocity_x, yaw, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, angular_velocity_y, angular_velocity_x, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, angular_velocity_z, angular_velocity_y, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, linear_acceleration_x, angular_velocity_z, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, linear_acceleration_y, linear_acceleration_x, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, linear_acceleration_z, linear_acceleration_y, 0),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, magnetic_field_x, linear_acceleration_z, 0),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, magnetic_field_y, magnetic_field_x, 0),
    PB_FIELD( 13, INT32   , OPTIONAL, STATIC  , OTHER, IMUData, magnetic_field_z, magnetic_field_y, 0),
    PB_LAST_FIELD
};

const pb_field_t SaberIMUData_fields[11] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SaberIMUData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, acc_x, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, acc_y, acc_x, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, acc_z, acc_y, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, gyro_x, acc_z, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, gyro_y, gyro_x, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, gyro_z, gyro_y, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, roll, gyro_z, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, pitch, roll, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, SaberIMUData, yaw, pitch, 0),
    PB_LAST_FIELD
};

const pb_field_t UltrasonicData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, UltrasonicData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, UltrasonicData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t ProtectorData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ProtectorData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ProtectorData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t AnalogAntiCollisionData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, AnalogAntiCollisionData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, AnalogAntiCollisionData, data, id, &UInt32Pair_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, AnalogAntiCollisionData, trigger_data, data, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t AntiDropData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, AntiDropData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, AntiDropData, data, id, &UInt32Pair_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, AntiDropData, trigger_data, data, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t UWBData_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, UWBData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, UWBData, x, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, UWBData, y, x, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, UWBData, z, y, 0),
    PB_LAST_FIELD
};

const pb_field_t UWBDistanceData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, UWBDistanceData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, UWBDistanceData, tag_num, id, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, UWBDistanceData, data, tag_num, &UWBDistanceData_UWBDistanceStruct_fields),
    PB_LAST_FIELD
};

const pb_field_t UWBDistanceData_UWBDistanceStruct_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, UWBDistanceData_UWBDistanceStruct, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, UWBDistanceData_UWBDistanceStruct, data, id, 0),
    PB_LAST_FIELD
};

const pb_field_t RFIDData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, RFIDData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, RFIDData, data, id, &RFIDData_RFIDStruct_fields),
    PB_LAST_FIELD
};

const pb_field_t RFIDData_RFIDStruct_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, RFIDData_RFIDStruct, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, RFIDData_RFIDStruct, data, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, RFIDData_RFIDStruct, strength, data, 0),
    PB_LAST_FIELD
};

const pb_field_t RemoteData433_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, RemoteData433, id, id, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, RemoteData433, data, id, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorDriverConfigData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotorDriverConfigData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, MotorDriverConfigData, config, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t HardwareDriverData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HardwareDriverData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HardwareDriverData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t OdomRecorderData_fields[9] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, OdomRecorderData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, odom_x, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, odom_y, odom_x, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, odom_w, odom_y, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, dx, odom_w, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, x, dx, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, y, x, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, OdomRecorderData, w, y, 0),
    PB_LAST_FIELD
};

const pb_field_t MCUDebugData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MCUDebugData, id, id, 0),
    PB_FIELD(  2, UINT32  , REPEATED, CALLBACK, OTHER, MCUDebugData, data, id, 0),
    PB_LAST_FIELD
};

const pb_field_t BatteryData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, BatteryData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, BatteryData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t ShaoTestData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ShaoTestData, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ShaoTestData, angular_velocity, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ShaoTestData, linear_velocity, angular_velocity, 0),
    PB_LAST_FIELD
};

const pb_field_t MotionPositionCammand_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotionPositionCammand, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MotionPositionCammand, left_position, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MotionPositionCammand, right_position, left_position, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, MotionPositionCammand, brake_cmd, right_position, 0),
    PB_LAST_FIELD
};

const pb_field_t OtherDeviceData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, OtherDeviceData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, OtherDeviceData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t DriverData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DriverData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DriverData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};
const pb_field_t HaideDeviceCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HaideDeviceCommand, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HaideDeviceCommand, command, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t HaideMotionData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HaideMotionData, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HaideMotionData, speed, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HaideMotionData, angle, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t HaideDeviceData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HaideDeviceData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HaideDeviceData, data, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};

const pb_field_t CANBusCommand_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CANBusCommand, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CANBusCommand, rtr, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, CANBusCommand, ide, rtr, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, CANBusCommand, can_id, ide, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, CANBusCommand, data, can_id, 0),
    PB_LAST_FIELD
};

const pb_field_t CANBusStatusData_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CANBusStatusData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CANBusStatusData, rtr, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, CANBusStatusData, ide, rtr, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, CANBusStatusData, can_id, ide, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, CANBusStatusData, data, can_id, 0),
    PB_LAST_FIELD
};

const pb_field_t PhantasMcuUpgradeCommand_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PhantasMcuUpgradeCommand, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommand, target, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommand, command_type, target, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommand, total_num, command_type, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommand, total_size, total_num, 0),
    PB_LAST_FIELD
};

const pb_field_t PhantasMcuUpgradePackage_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PhantasMcuUpgradePackage, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackage, target, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackage, sequence, target, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackage, crc, sequence, 0),
    PB_FIELD(  5, BYTES   , REQUIRED, CALLBACK, OTHER, PhantasMcuUpgradePackage, data, crc, 0),
    PB_LAST_FIELD
};

const pb_field_t PhantasMcuUpgradeCommandStatusData_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PhantasMcuUpgradeCommandStatusData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommandStatusData, status, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommandStatusData, command_type, status, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradeCommandStatusData, target, command_type, 0),
    PB_LAST_FIELD
};

const pb_field_t PhantasMcuUpgradePackageStatusData_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PhantasMcuUpgradePackageStatusData, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackageStatusData, status, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackageStatusData, target, status, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PhantasMcuUpgradePackageStatusData, sequence, target, 0),
    PB_LAST_FIELD
};

const pb_field_t PhantasMcuTypeData_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PhantasMcuTypeData, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, PhantasMcuTypeData, mcu_types, id, &UInt32Pair_fields),
    PB_LAST_FIELD
};
/* @@protoc_insertion_point(eof) */
